apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlezcano-playground
  namespace: dev # IMPORTANTE: debe ir en el namespace dev, tal y como indica el subject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
      - name: mlezcano-playground
        image: mikelezc/playground:v1
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: mlezcano-playground
  namespace: dev
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30080
  selector:
    app: playground
