# Este archivo es el que esta en el repositorio de github, y es el que se va a aplicar en el cluster de kubernetes. 
# Contiene la definicion del deployment y del service para la aplicacion mlezcano-playground. 
# Es importante que el namespace sea dev, tal y como indica el subject. 
# El deployment tiene una replica, y el service es de tipo NodePort, con el puerto 30080.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlezcano-playground
  namespace: dev # IMPORTANTE: debe ir en el namespace dev, tal y como indica el subject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: mlezcano-playground
        image: mikelezc/playground:v1
        env:
        - name: VERSION
          value: "v1" # Para cambiar la versión ponemos este número en 1 o en 2
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: mlezcano-playground
  namespace: dev
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30080
  selector:
    app: playground
